// <auto-generated />
using BuffteksWebsite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace BuffteksWebsite.Migrations
{
    [DbContext(typeof(BuffteksWebsiteContext))]
    [Migration("20180430070216_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("BuffteksWebsite.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Details");

                    b.Property<string>("ProjectName");

                    b.HasKey("ID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BuffteksWebsite.Models.ProjectParticiant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int?>("ProjectID");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectParticiant");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProjectParticiant");
                });

            modelBuilder.Entity("BuffteksWebsite.Models.Client", b =>
                {
                    b.HasBaseType("BuffteksWebsite.Models.ProjectParticiant");

                    b.Property<string>("ClientUserName");

                    b.Property<string>("Email");

                    b.Property<string>("Phone");

                    b.ToTable("Client");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("BuffteksWebsite.Models.Member", b =>
                {
                    b.HasBaseType("BuffteksWebsite.Models.ProjectParticiant");

                    b.Property<string>("Birthday");

                    b.Property<string>("Email")
                        .HasColumnName("Member_Email");

                    b.Property<string>("Major");

                    b.Property<string>("MemberUserName");

                    b.Property<string>("Phone")
                        .HasColumnName("Member_Phone");

                    b.Property<string>("Standing");

                    b.ToTable("Member");

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("BuffteksWebsite.Models.ProjectParticiant", b =>
                {
                    b.HasOne("BuffteksWebsite.Models.Project")
                        .WithMany("Participants")
                        .HasForeignKey("ProjectID");
                });
#pragma warning restore 612, 618
        }
    }
}
